### ISSUE TITLE
Inconsistent start/startdate documentation

### ISSUE THREAD

**Issue by P-Storm** [qwandor/dancelist-data#10]
Hi,

I was looking into why there were no dates for example `Balfolk Café Nijmegen with Androneda`. 

See https://github.com/qwandor/dancelist-data/blob/c2e98bd9bbebb0c07e5acd40d7793767097b7f09/events/netherlands/balfolk_nl.yaml#L7

Another entry that has it's date set:
https://github.com/qwandor/dancelist-data/blob/84d8c49e8d48c95eedf8370e174cddeb15bc6d32/events/belgium/folkbalbende.yaml#L7

This resulted in for example a json with the following fields:

* start_date
* end_date

And for the time set entry
* start
* end

This is inconsistent with the `event scheme` https://github.com/qwandor/dancelist-data/blob/c2e98bd9bbebb0c07e5acd40d7793767097b7f09/events_schema.json

This file doesn't have the time entries (start/end).

So to be concrete:

1. Can you update the `event_scheme.json` file to include start/end
2. Can you update the json to generate start_date/end_date when only start/end is given?

Point 2 should probably go into the repo of serving the website.

**Comment by qwandor** [comment]
Does [this version of the schema](https://raw.githubusercontent.com/qwandor/dancelist/main/events_schema.json) work for you? That's what the schema generation tool I'm using generates, but for some reason the [VSCode extension I'm using](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) doesn't seem to like it, which is why I didn't update it in this repository yet.

For your second point, the JSON, YAML and TOML all follow the same schema. The `start`/`end` fields already contain the date, so I don't want to duplicate this in the `start_date`/`end_date`. In fact [the way the data structures are designed](https://github.com/qwandor/dancelist/blob/main/src/model/event.rs#L70) serde requires exactly one pair to be present in each event, so it's not possible to have both.

**Comment by P-Storm** [comment]
The event_scheme.json looks good. I was thinking in a structure of need start_date/end_date, and if you have the info you can put in the start/end (with time component). But that means indeed that you have to edit things with serde, but this is also fine 👍

**Comment by P-Storm** [comment]
Will close this issue when you have figured it out how to let the proposed schema play nice :)
